apps/urls.py
from django.urls import include, path
from django.contrib import admin

import theme.views

urlpatterns = [
    path('', theme.views.home),
    path('books_cbv/', include('books_cbv.urls')),
    path('books_fbv/', include('books_fbv.urls')),
    path('books_fbv_user/', include('books_fbv_user.urls')),

    # Enable built-in authentication views
    path('accounts/', include('django.contrib.auth.urls')),    
    # Enable built-in admin interface
    path('admin/', admin.site.urls),
]

books_cbv/urls.py
from django.urls import path

from . import views

app_name = 'books_cbv'

urlpatterns = [
  path('', views.BookList.as_view(), name='book_list'),
  path('new/', views.BookCreate.as_view(), name='book_new'),
  path('edit/<int:pk>/', views.BookUpdate.as_view(), name='book_edit'),
  path('delete/<int:pk>/', views.BookDelete.as_view(), name='book_delete'),
]

books_fbv/urls.py
from django.urls import path

from books_fbv import views

app_name = 'books_fbv'

urlpatterns = [
  path('', views.book_list, name='book_list'),
  path('new/', views.book_create, name='book_new'),
  path('edit/<int:pk>/', views.book_update, name='book_edit'),
  path('delete/<int:pk>/', views.book_delete, name='book_delete'),
]

books_fbv_user/urls.py
from django.urls import path

from . import views

app_name = 'books_fbv_user'

urlpatterns = [
  path('', views.book_list, name='book_list'),
  path('new/', views.book_create, name='book_new'),
  path('edit/<int:pk>/', views.book_update, name='book_edit'),
  path('delete/<int:pk>/', views.book_delete, name='book_delete'),
]

books_cbv/models.py
from django.db import models
from django.urls import reverse


class Book(models.Model):
    name = models.CharField(max_length=200)
    pages = models.IntegerField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('books_cbv:book_edit', kwargs={'pk': self.pk})

books_fbv/models.py
from django.db import models
from django.urls import reverse


class Book(models.Model):
    name = models.CharField(max_length=200)
    pages = models.IntegerField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('books_fbv:book_edit', kwargs={'pk': self.pk})

books_fbv_user/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

class Book(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    pages = models.IntegerField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('books_fbv_user:book_edit', kwargs={'pk': self.pk})

theme/models.py
from django.db import models

# Create your models here.

apps/views.py
from django.shortcuts import render

books_cbv/views.py
from django.http import HttpResponse
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import Book

class BookList(ListView):
    model = Book

class BookCreate(CreateView):
    model = Book
    fields = ['name', 'pages']
    success_url = reverse_lazy('books_cbv:book_list')

class BookUpdate(UpdateView):
    model = Book
    fields = ['name', 'pages']
    success_url = reverse_lazy('books_cbv:book_list')

class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('books_cbv:book_list')

books_fbv/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm

from .models import Book

class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ['name', 'pages']

def book_list(request, template_name='books_fbv/book_list.html'):
    book = Book.objects.all()
    data = {}
    data['object_list'] = book
    return render(request, template_name, data)

def book_create(request, template_name='books_fbv/book_form.html'):
    form = BookForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('books_fbv:book_list')
    return render(request, template_name, {'form':form})

def book_update(request, pk, template_name='books_fbv/book_form.html'):
    book= get_object_or_404(Book, pk=pk)
    form = BookForm(request.POST or None, instance=book)
    if form.is_valid():
        form.save()
        return redirect('books_fbv:book_list')
    return render(request, template_name, {'form':form})

def book_delete(request, pk, template_name='books_fbv/book_confirm_delete.html'):
    book= get_object_or_404(Book, pk=pk)    
    if request.method=='POST':
        book.delete()
        return redirect('books_fbv:book_list')
    return render(request, template_name, {'object':book})

books_fbv_user/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm

from .models import Book

class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ['name', 'pages']

@login_required
def book_list(request, template_name='books_fbv_user/book_list.html'):
    if request.user.is_superuser:
        book = Book.objects.all()
    else:
        book = Book.objects.filter(user=request.user)
    data = {}
    data['object_list'] = book
    return render(request, template_name, data)

@login_required
def book_create(request, template_name='books_fbv_user/book_form.html'):
    form = BookForm(request.POST or None)
    if form.is_valid():
        book = form.save(commit=False)
        book.user = request.user
        book.save()
        return redirect('books_fbv_user:book_list')
    return render(request, template_name, {'form':form})

@login_required
def book_update(request, pk, template_name='books_fbv_user/book_form.html'):
    if request.user.is_superuser:
        book= get_object_or_404(Book, pk=pk)
    else:
        book= get_object_or_404(Book, pk=pk, user=request.user)
    form = BookForm(request.POST or None, instance=book)
    if form.is_valid():
        form.save()
        return redirect('books_fbv_user:book_list')
    return render(request, template_name, {'form':form})

@login_required
def book_delete(request, pk, template_name='books_fbv_user/book_confirm_delete.html'):
    if request.user.is_superuser:
        book= get_object_or_404(Book, pk=pk)
    else:
        book= get_object_or_404(Book, pk=pk, user=request.user)
    if request.method=='POST':
        book.delete()
        return redirect('books_fbv_user:book_list')
    return render(request, template_name, {'object':book})

theme/views.py
from django.shortcuts import render

def home(request):
    return render(request, "home.html")

books_cbv/templates/books_cbv/book_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'books_cbv:book_list' %}">Books CBV</a>: Delete?</h2>

<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?<br>
    <input type="submit" value="Delete" />
</form>

{% endblock %}

books_cbv/templates/books_cbv/book_form.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'books_cbv:book_list' %}">Books CBV</a>: Edit</h2>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

{% endblock %}

books_cbv/templates/books_cbv/book_list.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'books_cbv:book_list' %}">Books CBV</a></h2>

<ul>
    {% for book in object_list %}
    <li>{{ book.name }}  ({{ book.pages }} Pages)
    <a href="{% url 'books_cbv:book_edit' book.id %}">edit</a>
    <a href="{% url 'books_cbv:book_delete' book.id %}">delete</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url 'books_cbv:book_new' %}">New</a>

{% endblock %}

books_fbv/templates/books_fbv/book_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'books_fbv:book_list' %}">Books FBV</a>: Delete?</h2>

<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?<br/>
    <input type="submit" value="Delete" />
</form>

{% endblock %}

books_fbv/templates/books_fbv/book_form.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'books_fbv:book_list' %}">Books FBV</a>: Edit</h2>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

{% endblock %}

books_fbv/templates/books_fbv/book_list.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'books_fbv:book_list' %}">Books FBV</a></h2>

<ul>
    {% for book in object_list %}
    <li>{{ book.name }}  ({{ book.pages }} Pages)
    <a href="{% url 'books_fbv:book_edit' book.id %}">edit</a>
    <a href="{% url 'books_fbv:book_delete' book.id %}">delete</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url 'books_fbv:book_new' %}">New</a>

{% endblock %}

books_fbv_user/templates/books_fbv_user/book_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'books_fbv_user:book_list' %}">Books FBV User</a>: Delete?</h2>

<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?<br/>
    <input type="submit" value="Delete" />
</form>

{% endblock %}

books_fbv_user/templates/books_fbv_user/book_form.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'books_fbv_user:book_list' %}">Books FBV User</a>: Edit</h2>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

{% endblock %}

books_fbv_user/templates/books_fbv_user/book_list.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'books_fbv_user:book_list' %}">Books FBV User</a></h2>

<ul>
    {% for book in object_list %}
    <li>{{ book.name }}  ({{ book.pages }} Pages)
    <a href="{% url 'books_fbv_user:book_edit' book.id %}">edit</a>
    <a href="{% url 'books_fbv_user:book_delete' book.id %}">delete</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url 'books_fbv_user:book_new' %}">New</a>

{% endblock %}

theme/templates/base.html
{% load static %}

<html>
<head>
    <title></title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
    <div id="header">
        {% if user.is_authenticated %}
        <div id="user">
            Hello {{ user }}, <a href="{% url 'logout' %}">Logout</a>
        </div>
        {% endif %}
        <h1><a href="/">Django CRUD Example</a></h1>
    </div><!-- header -->
    <div id="content">
        {% block content %}
        {% endblock %}
    </div><!-- content -->
    <div id="footer">
    </div>
</body>
</html>

theme/templates/home.html
{% extends "base.html" %}

{% block content %}

<a href="{% url 'books_cbv:book_list' %}">Class Based Views</a><br>
<a href="{% url 'books_fbv:book_list' %}">Function Based Views</a><br>    
<a href="{% url 'books_fbv_user:book_list' %}">Function Based Views with User Access</a><br>    

{% endblock %}